### PR TITLE
Added Kinetics Toolkit

### PR DESCRIPTION
**Pull request by felixchenier**
Good morning

Thank you for your nice and exhaustive list! I added Kinetics Toolkit, an open source python library I develop for my lab, which I think would fit well in your list.

Sincerely,

Félix Chénier

### CODE REVIEW

**Comment by modenaxe** [comment]
Hi Félix, 
very nice Python module and documentation, thank you for adding it to the list!
Best wishes,
Luca

**Comment by modenaxe** [comment]
@felixchenier with this level of documentation you could probably consider submitting the repository to [JOSS](https://joss.theoj.org/) as well (just a suggestion).

**Comment by felixchenier** [comment]
@modenaxe Thanks for your kind comments. JOSS is effectively on the road map, I'm just waiting to release a couple more essential modules before committing a white paper. Possibly with the next version, which should include kinematic reconstruction tools and possibly inverse dynamic calculation.

All the best,

Félix

**Comment by modenaxe** [comment]
looking forward to the next releases then!

**Pull request merged**
